### ISSUE TITLE
Not actually design for dark background

### ISSUE THREAD

**Issue by dtlnor** [iAvoe/x265-web-tutorial#7]
https://github.com/iAvoe/x265-web-tutorial/blob/31effd4dfd83af09f0cc2913c1a2fe8b283dead2/README.md?plain=1#L10

![image](https://github.com/iAvoe/x265-web-tutorial/assets/21131439/ac080c48-9644-4b3e-a363-a9e0191fbb70)
![image](https://github.com/iAvoe/x265-web-tutorial/assets/21131439/f15ceebd-ea8f-4b4b-9970-ff4e4b78c0ae)

Pictures in dark mode are screw up

**Comment by iAvoe** [comment]
Fixed: https://github.com/iAvoe/x265-web-tutorial/commit/18bda5bb2ecfed518bfc6769d2460e888bfd7ef8
